# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /blog/:categories/:year/:month/:day/:title.html

# Setup
title:            Moroccan PHP Artisans
tagline:          'PHP User Group'
url:              http://moroccanphpartisans.github.io
email: 			  'mphpartisans@gmail.com'
paginate:         5
paginate_path: 	  "/blog/page:num"


# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MoroccanPHPArtisans/moroccanphpartisans.github.io